#ifndef _HYPEREDGE_VIEWER_HPP
#define _HYPEREDGE_VIEWER_HPP

#include <QWidget>
#include <QGraphicsView>
#include <QMap>
#include "Hyperedge.hpp"
#include "Hypergraph.hpp"

// Generated by MOC
namespace Ui
{
    class HyperedgeViewer;
}

// Forward decls
class QGraphicsScene;
class QGraphicsView;

class Hyperedge;
class HyperedgeItem;

class HyperedgeScene : public QGraphicsScene
{
    Q_OBJECT

    public:
        HyperedgeScene(QObject * parent = 0);
        ~HyperedgeScene();

        void addItem(QGraphicsItem *item);
        void removeItem(QGraphicsItem *item);
        Hyperedge::Hyperedges getAllEdges()
        {
            return currentGraph->find();
        }
        Hypergraph* graph()
        {
            return currentGraph;
        }

    signals:
        // Signals emitted
        void edgeAdded(const unsigned int id);
        void edgeRemoved(const unsigned int id);
        void edgesConnected(const unsigned int fromId, const unsigned int toId);

    public slots:
        // This is the constructing function of the hyperedge scene
        void visualize(Hypergraph* graph = NULL);

        // Slots to modify the underlying hyperedge system
        void addEdge(const QString& label="");
        void addEdgeAndConnect(const unsigned int toId, const QString& label="");
        void removeEdge(const unsigned int id);
        void connectEdges(const unsigned int fromId, const unsigned int toId);
        void updateEdge(const unsigned int id, const QString& label);

    private:
        Hypergraph *currentGraph;
        QMap<unsigned int, HyperedgeItem*> currentItems;
};

class ForceBasedScene : public HyperedgeScene
{
    Q_OBJECT

    public:
        ForceBasedScene(QObject * parent = 0);
        ~ForceBasedScene();

        // Adjust these if needed
        bool isEnabled();

    public slots:
        // Cycles through all items of a scene and updates the positions of hyperedgeitems according to their neighbours
        // Calls the base class visualizer as well
        void visualize(Hypergraph* graph = NULL);
        void setEnabled(bool enable);
        void setEquilibriumDistance(qreal distance);

    private:
        QTimer *mpTimer;
        qreal mEquilibriumDistance;
};

class HyperedgeView : public QGraphicsView
{
    Q_OBJECT

    public:
        HyperedgeView(QWidget *parent = 0);
        HyperedgeView(HyperedgeScene * scene, QWidget * parent = 0 );

        HyperedgeScene* scene()
        {
            return dynamic_cast<HyperedgeScene*>(QGraphicsView::scene());
        }

    protected:
        /// qt mouse wheel spin callback
        void wheelEvent(QWheelEvent *event);
        /// scales scene (zooms into or out of the scene)
        void scaleView(qreal scaleFactor);

        // Mouse press and release event to move view
        void mousePressEvent(QMouseEvent*);
        void mouseReleaseEvent(QMouseEvent*);
};

class HyperedgeEdit : public HyperedgeView
{
    Q_OBJECT

    public:
        HyperedgeEdit(QWidget *parent = 0);
        HyperedgeEdit(HyperedgeScene * scene, QWidget * parent = 0 );

    signals:
        // emitted by setDefaultLabel()
        void labelChanged(const QString& label);

    public slots:
        // Call this to set the label of all edges to be created in the future
        void setDefaultLabel(const QString& label);

    protected:
        // Mouse press and release event to select and connect things
        void mousePressEvent(QMouseEvent*);
        void mouseMoveEvent(QMouseEvent*);
        void mouseReleaseEvent(QMouseEvent*);

        // Keyboard event to
        // a) delete edges (Del)
        // b) insert edges (Ins)
        void keyPressEvent(QKeyEvent * event);

    private:
        // DRAW_LINE mode
        bool isDrawLineMode;
        HyperedgeItem* sourceItem;
        QGraphicsLineItem *lineItem;

        // SELECT_OBJECT mode
        HyperedgeItem* selectedItem;

        // ADD NEW mode
        bool isEditLabelMode;
        QString currentLabel;
};


class HyperedgeViewer : public QWidget
{
    Q_OBJECT

    public:
        HyperedgeViewer(QWidget *parent = 0);
        ~HyperedgeViewer();

    signals:
        // Will be emitted by storeToYAML if generation is finished
        void YAMLStringReady(const QString& yamlString);

    public slots:
        // Load a hyperedge system (= hypergraph) from YAML file
        void loadFromYAMLFile(const QString& fileName);
        // Load a hyperedge system (= hypergraph) from YAML string
        void loadFromYAML(const QString& yamlString);
        // Store a hyperedge system (= hypergraph) to a YAML string
        void storeToYAML();
        // Clear everything
        void clearHyperedgeSystem();

    private:
        Ui::HyperedgeViewer* mpUi;

        ForceBasedScene*    mpScene;
        HyperedgeEdit*      mpView;
};

#endif

