#ifndef _HYPERGRAPH_GUI_HPP
#define _HYPERGRAPH_GUI_HPP

#include <QMainWindow>

// Generated by MOC
namespace Ui
{
    class HypergraphGUI;
}

// Forward declarations
class HypergraphViewer;
class ConceptgraphViewer;
class HypergraphControl;

class HypergraphGUI : public QMainWindow
{
    Q_OBJECT

    public:
        HypergraphGUI(QWidget *parent = 0);
        ~HypergraphGUI();

    public slots:
        void clearHypergraphRequest();
        void loadHypergraphRequest();
        void storeHypergraphRequest();
        void onYAMLStringReady(const QString& yamlString);

    private:
        Ui::HypergraphGUI* mpUi;

        // Add hyperedge viewer
        HypergraphViewer*    mpHedgeViewer;
        ConceptgraphViewer* mpConceptViewer;

        // Add hyperedge control
        HypergraphControl* mpControl;
        QString lastOpenedFile;
        QString lastSavedFile;
};

#endif
