#ifndef _HYPERGRAPH_VIEWER_HPP
#define _HYPERGRAPH_VIEWER_HPP

#include <QWidget>
#include <QGraphicsView>
#include <QMap>
#include "Hyperedge.hpp"
#include "Hypergraph.hpp"

// Generated by MOC
namespace Ui
{
    class HypergraphViewer;
}

// Forward decls
class QGraphicsScene;
class QGraphicsView;

class Hyperedge;
class HyperedgeItem;

class HypergraphScene : public QGraphicsScene
{
    Q_OBJECT

    public:
        HypergraphScene(QObject * parent = 0);
        ~HypergraphScene();

        void addItem(QGraphicsItem *item);
        void removeItem(QGraphicsItem *item);
        Hypergraph::Hyperedges getAllEdges()
        {
            return currentGraph->find();
        }
        Hypergraph* graph()
        {
            return currentGraph;
        }
        bool isEnabled() { return mEnabled; }
        QList<HyperedgeItem*> selectedHyperedgeItems();

    signals:
        // Signals emitted
        void edgeAdded(const unsigned int id);
        void edgeRemoved(const unsigned int id);
        void edgesConnected(const unsigned int fromId, const unsigned int toId);

    public slots:
        // This is the constructing function of the hyperedge scene
        void visualize(Hypergraph* graph = NULL);
        // Enable visualization
        void setEnabled(bool enable) { mEnabled = enable; }

        // Slots to modify the underlying hyperedge system
        void addEdge(const QString& label="");
        void removeEdge(const unsigned int id);
        void connectEdges(const unsigned int fromId, const unsigned int id, const unsigned int toId);
        void updateEdge(const unsigned int id, const QString& label);

    protected:
        bool mEnabled;
        Hypergraph *currentGraph;
        QMap<unsigned int, HyperedgeItem*> currentItems;
};

class ForceBasedScene : public HypergraphScene
{
    Q_OBJECT

    public:
        ForceBasedScene(QObject * parent = 0);
        ~ForceBasedScene();

    public slots:
        // Cycles through all items of a scene and updates the positions of hyperedgeitems according to their neighbours
        void updateLayout();
        void setEquilibriumDistance(qreal distance);
        // Enable visualization (and also Timer!)
        void setEnabled(bool enable);

    private:
        QTimer *mpTimer;
        qreal mEquilibriumDistance;
};

class HypergraphView : public QGraphicsView
{
    Q_OBJECT

    public:
        HypergraphView(QWidget *parent = 0);
        HypergraphView(HypergraphScene * scene, QWidget * parent = 0 );

        HypergraphScene* scene()
        {
            return dynamic_cast<HypergraphScene*>(QGraphicsView::scene());
        }

    protected:
        /// qt mouse wheel spin callback
        void wheelEvent(QWheelEvent *event);
        /// scales scene (zooms into or out of the scene)
        void scaleView(qreal scaleFactor);

        // Mouse press and release event to move view
        void mousePressEvent(QMouseEvent*);
        void mouseReleaseEvent(QMouseEvent*);
};

class HypergraphEdit : public HypergraphView
{
    Q_OBJECT

    public:
        HypergraphEdit(QWidget *parent = 0);
        HypergraphEdit(HypergraphScene * scene, QWidget * parent = 0 );

    signals:
        // emitted by setDefaultLabel()
        void labelChanged(const QString& label);

    public slots:
        // Call this to set the label of all edges to be created in the future
        void setDefaultLabel(const QString& label);

    protected:
        // Mouse press and release event to select and connect things
        void mousePressEvent(QMouseEvent*);
        void mouseMoveEvent(QMouseEvent*);
        void mouseReleaseEvent(QMouseEvent*);

        // Keyboard event to
        // a) delete edges (Del)
        // b) insert edges (Ins)
        void keyPressEvent(QKeyEvent * event);

    private:
        // DRAW_LINE mode
        bool isDrawLineMode;
        HyperedgeItem* sourceItem;
        QGraphicsLineItem *lineItem;

        // ADD NEW mode
        bool isEditLabelMode;
        QString currentLabel;
};


class HypergraphViewer : public QWidget
{
    Q_OBJECT

    public:
        HypergraphViewer(QWidget *parent = 0);
        ~HypergraphViewer();

    signals:
        // Will be emitted by storeToYAML if generation is finished
        void YAMLStringReady(const QString& yamlString);

    public slots:
        // Load a hyperedge system (= hypergraph) from YAML file
        void loadFromYAMLFile(const QString& fileName);
        // Load a hyperedge system (= hypergraph) from YAML string
        void loadFromYAML(const QString& yamlString);
        // Store a hyperedge system (= hypergraph) to a YAML string
        void storeToYAML();
        // Clear everything
        void clearHypergraph();

    protected:
        // Triggered when widget is about to get visible
        void showEvent(QShowEvent *event);
        // Triggered when widget is about to get hidden
        void hideEvent(QHideEvent *event);

    private:
        Ui::HypergraphViewer* mpUi;

        ForceBasedScene*    mpScene;
        HypergraphEdit*      mpView;
};

#endif

