#ifndef _HYPERGRAPH_GUI_HPP
#define _HYPERGRAPH_GUI_HPP

#include <QMainWindow>
#include "HypergraphTypes.hpp"

// Generated by MOC
namespace Ui
{
    class HypergraphGUI;
}

// Forward declarations
class QTabWidget;
class HypergraphControl;

class HypergraphGUI : public QMainWindow
{
    Q_OBJECT

    public:
        HypergraphGUI(QWidget *parent = 0);
        ~HypergraphGUI();

    public slots:
        void clearHypergraphRequest();
        void newHypergraphRequest(HypergraphType type);
        void loadHypergraphRequest(HypergraphType type);
        void storeHypergraphRequest();
        void onYAMLStringReady(const QString& yamlString);
        void setEquilibriumDistanceRequest(qreal distance);

    private:
        Ui::HypergraphGUI* mpUi;

        // The tab widget holding all viewers
        QTabWidget*     mpViewerTabWidget;
        
        // Add hyperedge control
        HypergraphControl* mpControl;
        QString lastOpenedFile;
        QString lastSavedFile;
};

#endif
