#ifndef _HYPEREDGE_CONTROL_HPP
#define _HYPEREDGE_CONTROL_HPP

#include <QWidget>

// Generated by MOC
namespace Ui
{
    class HyperedgeControl;
}

class HyperedgeControl : public QWidget
{
    Q_OBJECT
    
    public:
        HyperedgeControl(QWidget *parent = 0);
        ~HyperedgeControl();

    signals:
        // Signals emitted by Buttons or something else
        void clearHyperedgeSystem();
        void loadHyperedgeSystem();
        void storeHyperedgeSystem();

    public slots:
        // To be autoconnected
        void on_loadButton_clicked();
        void on_saveButton_clicked();
        void on_clearButton_clicked();

    private:
        Ui::HyperedgeControl *mpUi;
};

#endif
