#ifndef _HYPERGRAPH_CONTROL_HPP
#define _HYPERGRAPH_CONTROL_HPP

#include <QWidget>
#include "HypergraphTypes.hpp"

// Generated by MOC
namespace Ui
{
    class HypergraphControl;
}

class HypergraphControl : public QWidget
{
    Q_OBJECT
    
    public:
        HypergraphControl(QWidget *parent = 0);
        ~HypergraphControl();

    signals:
        // Signals emitted by Buttons or something else
        void newHypergraph(HypergraphType type);
        void clearHypergraph();
        void loadHypergraph(HypergraphType type);
        void storeHypergraph();
        void setEquilibriumDistance(qreal distance);

    public slots:
        // To be autoconnected
        void on_newButton_clicked();
        void on_loadButton_clicked();
        void on_saveButton_clicked();
        void on_clearButton_clicked();

        void on_equiSlider_valueChanged(int value);
        void on_equiBox_valueChanged(int value);

    private:
        Ui::HypergraphControl *mpUi;
};

#endif
