#ifndef _HYPERGRAPH_CONTROL_HPP
#define _HYPERGRAPH_CONTROL_HPP

#include <QWidget>

// Generated by MOC
namespace Ui
{
    class HypergraphControl;
}

class HypergraphControl : public QWidget
{
    Q_OBJECT
    
    public:
        HypergraphControl(QWidget *parent = 0);
        ~HypergraphControl();

    signals:
        // Signals emitted by Buttons or something else
        void clearHypergraph();
        void loadHypergraph();
        void storeHypergraph();

    public slots:
        // To be autoconnected
        void on_loadButton_clicked();
        void on_saveButton_clicked();
        void on_clearButton_clicked();

    private:
        Ui::HypergraphControl *mpUi;
};

#endif
