#ifndef _HYPEREDGE_GUI_HPP
#define _HYPEREDGE_GUI_HPP

#include <QMainWindow>

// Generated by MOC
namespace Ui
{
    class HyperedgeGUI;
}

// Forward declarations
class HyperedgeViewer;
class ConceptgraphViewer;
class HyperedgeControl;

class HyperedgeGUI : public QMainWindow
{
    Q_OBJECT

    public:
        HyperedgeGUI(QWidget *parent = 0);
        ~HyperedgeGUI();

    public slots:
        void clearHyperedgeSystemRequest();
        void loadHyperedgeSystemRequest();
        void storeHyperedgeSystemRequest();
        void onYAMLStringReady(const QString& yamlString);

    private:
        Ui::HyperedgeGUI* mpUi;

        // Add hyperedge viewer
        HyperedgeViewer*    mpHedgeViewer;
        ConceptgraphViewer* mpConceptViewer;

        // Add hyperedge control
        HyperedgeControl* mpControl;
        QString lastOpenedFile;
        QString lastSavedFile;
};

#endif
